CREATE TYPE role AS ENUM ('USER', 'ADMIN');
CREATE TYPE status AS ENUM ('ACTIVE', 'BLOCKED');
CREATE TYPE gender AS ENUM ('NB', 'MALE', 'FEMALE');

DROP TYPE role;
DROP TYPE status;
DROP TYPE gender;


CREATE TABLE Person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name varchar(100),
                       username varchar(40) NOT NULL UNIQUE,
                       password varchar(50) NOT NULL,
                       email varchar(50) NOT NULL UNIQUE,
                       telephone decimal(20) UNIQUE,
                       about varchar(100),
                       status status,
                       gender gender,
                       role role,
                       date_of_birth date
);

CREATE TABLE Address(
                        person_id int NOT NULL REFERENCES Person(id) ON DELETE SET NULL,
                        country varchar(50) NOT NULL,
                        city varchar(50) NOT NULL,
                        street varchar(50) NOT NULL,
                        house_number int NOT NULL,
                        apartment_number int NULL
);

CREATE TABLE User_wallet(
                            person_id int NOT NULL REFERENCES Person(id) ON DELETE SET NULL,
                            deposit money
);

CREATE TABLE Sponsor(
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        sponsor_name varchar(100) NOT NULL,
                        description varchar(100) NOT NULL,
                        user_check varchar(100) NOT NULL,
                        person_id int NOT NULL REFERENCES Person(id) ON DELETE SET NULL
);

CREATE TABLE Game(
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     person_id int NOT NULL REFERENCES Person(id) ON DELETE SET NULL,
                     game_name varchar(50) NOT NULL,
                     game_date date NOT NULL
);

CREATE TABLE Support_request(
                                request_date date NOT NULL,
                                person_id int NOT NULL REFERENCES Person(id) ON DELETE SET NULL,
                                game_id int NOT NULL REFERENCES Game(id) ON DELETE SET NULL,
                                subject varchar(50),
                                content varchar(500),
                                request_status boolean
);

DROP TABLE Address;
DROP TABLE User_wallet;
DROP TABLE Sponsor;
DROP TABLE Support_request;
DROP TABLE Game;
DROP TABLE Person;

TRUNCATE TABLE Person;

INSERT INTO Person (full_name, username, password, email, telephone, about, status, gender, role, date_of_birth)
VALUES ('Oleg', 'user1', 'pass1', 'mail1@mail.ru', +79999999999, 'About1', 'ACTIVE', 'MALE', 'USER', '13.03.1991');
INSERT INTO Person (full_name, username, password, email, telephone, about, status, gender, role, date_of_birth)
VALUES ('Nika', 'user2', 'pass2', 'mail2@mail.ru', +78888888888, 'About2', 'ACTIVE', 'FEMALE', 'ADMIN', '22.05.1999');
INSERT INTO Person (full_name, username, password, email, telephone, about, status, gender, role, date_of_birth)
VALUES ('Sasha', 'user3', 'pass3', 'mail3@mail.ru', +77777777777, 'About3', 'ACTIVE', 'NB', 'USER', '04.10.1985');